const savedKey='danang-slow-shortlist-v2';
const places=[
 {id:'intercontinental',type:'resort',name:'InterContinental Danang Sun Peninsula',short:'山茶半島・隱世奢華',lat:16.1187,lng:108.2865,why:'坐落山茶半島自然保護區，面向私密海灣；適合想把森林、海景與頂級餐飲都留在飯店裡的人。',tags:['私密海灣','設計感','美食'],official:'https://www.danang.intercontinental.com/about/',map:'InterContinental Danang Sun Peninsula Resort'},
 {id:'tia',type:'resort',name:'TIA Wellness Resort',short:'農水海灘・療癒充電',lat:16.0207,lng:108.2538,why:'私人泳池 villa 與 Wellness Inclusive 概念，把 SPA、呼吸練習與慢下來的節奏排進住宿本身。',tags:['身心療癒','私人泳池','SPA'],official:'https://tiawellnessresort.com/',map:'TIA Wellness Resort Da Nang'},
 {id:'hyatt',type:'resort',name:'Hyatt Regency Danang',short:'農水海灘・親子與平衡',lat:16.0009,lng:108.2634,why:'海灘、VIE Spa、水上活動與兒童活動兼具；適合同行者需求不同、又不想犧牲度假感的一群人。',tags:['親子友善','水上活動','SPA'],official:'https://www.hyatt.com/hyatt-regency/en-US/danhr-hyatt-regency-danang-resort-and-spa',map:'Hyatt Regency Danang Resort and Spa'},
 {id:'naman',type:'resort',name:'Naman Retreat',short:'農水海灘・靜謐設計',lat:15.9888,lng:108.2699,why:'以越南竹構建築和成熟的 SPA 風格聞名；若你想住在設計感更強、距離五行山不遠的海邊，值得比較。',tags:['設計旅宿','靜謐','SPA'],official:'https://www.namanretreat.com/',map:'Naman Retreat Da Nang'},
 {id:'namhai',type:'resort',name:'Four Seasons Resort The Nam Hai',short:'會安・海岸隱居',lat:15.9138,lng:108.3266,why:'在會安北側的海岸，適合把重心放在慢住、文化體驗與會安古鎮的傍晚；適合行程天數較寬裕時。',tags:['會安基地','文化感','海岸'],official:'https://www.fourseasons.com/hoian/',map:'Four Seasons Resort The Nam Hai Hoi An'},
 {id:'sontra',type:'place',name:'山茶半島與靈應寺',short:'自然・半日景觀路線',lat:16.0966,lng:108.2809,why:'森林、山路與海岸視野在同一個半島。清晨或傍晚光線舒服，也較適合不趕時間的探索。',tags:['山海景','野生動物','日落'],official:'https://www.vietnam.travel/things-to-do/must-visit-places-in-da-nang',map:'Son Tra Peninsula Da Nang'},
 {id:'mykhe',type:'place',name:'美溪海灘',short:'海灘・日出與咖啡',lat:16.0602,lng:108.2463,why:'峴港最方便靠近城市的長海灘。清晨散步、游泳，或把它當成飯店外的一段鬆弛時光。',tags:['日出','城市海灘','咖啡'],official:'https://www.vietnam.travel/things-to-do/must-do-da-nang-an-insider-list',map:'My Khe Beach Da Nang'},
 {id:'marble',type:'place',name:'五行山',short:'文化・洞穴與俯瞰',lat:16.0038,lng:108.2636,why:'石灰岩山、石窟與寺廟交織；從農水海灘一帶出發最順，建議避開正午炎熱時段。',tags:['寺廟','洞穴','登高'],official:'https://www.vietnam.travel/things-to-do/must-visit-places-in-da-nang',map:'Marble Mountains Da Nang'},
 {id:'hoian',type:'place',name:'會安古城',short:'夜晚・燈籠與河岸',lat:15.8801,lng:108.3380,why:'更適合傍晚抵達：逛古城、吃晚餐、沿河慢走。若住在會安北側，能把往返感降到最低。',tags:['古城','晚餐','夜景'],official:'https://www.vietnamtourism.com/en/visiting-da-nang-your-complete-travel-guide-to-vietnam-s-coastal-city',map:'Hoi An Ancient Town'},
 {id:'haivan',type:'place',name:'海雲關',short:'公路・山海展望',lat:16.2034,lng:108.1361,why:'從峴港往北的經典海岸山路。適合預留半天以上，以包車或熟悉路況的交通方式慢慢走。',tags:['公路旅行','山海景','半日'],official:'https://www.vietnam.travel/things-to-do/must-visit-places-in-da-nang',map:'Hai Van Pass'}
];
let saved=JSON.parse(localStorage.getItem(savedKey)||'[]'),activeFilter='all',map,markers=[];
const mapsUrl=p=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.map)}`;
const byId=id=>places.find(p=>p.id===id);
function save(){localStorage.setItem(savedKey,JSON.stringify(saved));renderSaved()}
function detail(p){const selected=saved.includes(p.id);document.querySelector('#placeDetail').innerHTML=`<span class="detail-kicker">${p.type==='resort'?'渡假村基地':'景點／體驗'} · ${p.short}</span><h3>${p.name}</h3><p>${p.why}</p><div class="detail-tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="detail-links"><a href="${mapsUrl(p)}" target="_blank" rel="noopener">在 Google Maps 開啟 ↗</a><a href="${p.official}" target="_blank" rel="noopener">查看相關介紹／文章 ↗</a><button class="save-place ${selected?'saved':''}" data-id="${p.id}">${selected?'已加入候選 ✓':'加入我的候選'}</button></div>`;document.querySelector('.save-place').onclick=e=>toggle(e.currentTarget.dataset.id)}
function toggle(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];save();detail(byId(id));renderCards()}
function markerIcon(type){return L.divIcon({className:'map-marker '+type,html:`<span></span>`,iconSize:[18,18],iconAnchor:[9,9]})}
function renderMarkers(){markers.forEach(m=>map.removeLayer(m));markers=[];places.filter(p=>activeFilter==='all'||p.type===activeFilter).forEach(p=>{const m=L.marker([p.lat,p.lng],{icon:markerIcon(p.type)}).addTo(map);m.on('click',()=>detail(p));markers.push(m)})}
function renderCards(){const box=document.querySelector('#resortCards');box.innerHTML=places.filter(p=>p.type==='resort').map(p=>`<article class="resort-card"><span>${p.short}</span><h3>${p.name}</h3><p>${p.why}</p><button data-id="${p.id}">${saved.includes(p.id)?'已在候選清單 ✓':'查看地圖資訊 →'}</button></article>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const p=byId(b.dataset.id);detail(p);map.flyTo([p.lat,p.lng],12,{duration:.7});document.querySelector('#explore').scrollIntoView({behavior:'smooth'})})}
function renderSaved(){const box=document.querySelector('#savedList');if(!saved.length){box.innerHTML='<p class="empty">還沒有候選地點。從地圖或渡假村卡開始收藏吧。</p>';return}box.innerHTML=saved.map(id=>{const p=byId(id);return `<article class="saved"><span class="saved-type">${p.type==='resort'?'渡假村基地':'景點／體驗'}</span><h3>${p.name}</h3><p>${p.short}</p><div><a href="${mapsUrl(p)}" target="_blank" rel="noopener">Google Maps ↗</a><button data-id="${p.id}">移除</button></div></article>`}).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>toggle(b.dataset.id))}
function init(){map=L.map('map',{scrollWheelZoom:false}).setView([16.01,108.27],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);renderMarkers();renderCards();renderSaved();document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderMarkers()});document.querySelector('#clearSaved').onclick=()=>{saved=[];save();renderCards()}}
init();
