const key = 'danang-slow-plan-v1';
const $ = (s) => document.querySelector(s);
let state = JSON.parse(localStorage.getItem(key) || '{"wishes":[],"pace":"悠閒渡假","days":{}}');
const save = () => localStorage.setItem(key, JSON.stringify(state));
const dateText = (date) => new Intl.DateTimeFormat('zh-TW',{month:'long',day:'numeric',weekday:'short'}).format(date);
function renderDays(){ const box=$('#days'); box.innerHTML=''; const start=$('#startDate').value; const end=$('#endDate').value; let dates=[]; if(start&&end&&new Date(end)>=new Date(start)){for(let d=new Date(start+'T00:00:00'), i=1;d<=new Date(end+'T00:00:00');d.setDate(d.getDate()+1),i++)dates.push({id:d.toISOString().slice(0,10),label:`第 ${i} 天`,date:new Date(d)})}else{dates=[{id:'day1',label:'第 1 天',date:null},{id:'day2',label:'第 2 天',date:null},{id:'day3',label:'第 3 天',date:null}]}; const template=$('#dayTemplate'); dates.forEach(({id,label,date}, dayIndex)=>{const node=template.content.cloneNode(true);node.querySelector('.day-number').textContent=String(dayIndex+1).padStart(2,'0'); node.querySelector('h3').textContent=label;node.querySelector('.day-heading p').textContent=date?dateText(date):'選擇日期後會自動更新';node.querySelectorAll('textarea').forEach((area,i)=>{area.value=(state.days[id]||[])[i]||'';area.addEventListener('input',()=>{state.days[id]=[...node.querySelectorAll('textarea')].map(x=>x.value);save()})});box.append(node)})}
function renderWishes(){const list=$('#wishList');list.innerHTML='';if(!state.wishes.length){list.innerHTML='<li class="empty">從上方的靈感卡開始收藏吧。</li>';return}state.wishes.forEach((wish,i)=>{const li=document.createElement('li');li.textContent=wish;const b=document.createElement('button');b.textContent='×';b.ariaLabel='移除';b.onclick=()=>{state.wishes.splice(i,1);save();renderWishes()};li.append(b);list.append(li)})}
function loadSetup(){['startDate','endDate','resort','area','priority'].forEach(id=>{const v=state[id];if(v!==undefined)$('#'+id).value=v});$('#paceLabel').textContent=state.pace;document.querySelectorAll('.pace').forEach(b=>b.classList.toggle('active',b.dataset.pace===state.pace))}
$('#saveSetup').onclick=()=>{['startDate','endDate','resort','area','priority'].forEach(id=>state[id]=$('#'+id).value);save();renderDays();$('#saveSetup').innerHTML='已儲存 <span>✓</span>';setTimeout(()=>$('#saveSetup').innerHTML='儲存這趟旅行 <span>→</span>',1500)};
document.querySelectorAll('.pace').forEach(b=>b.onclick=()=>{state.pace=b.dataset.pace;save();loadSetup()});
document.querySelectorAll('.add-idea').forEach(b=>b.onclick=()=>{if(!state.wishes.includes(b.dataset.title)){state.wishes.push(b.dataset.title);save();renderWishes()}b.textContent='已收進清單 ✓';setTimeout(()=>b.textContent='加入願望清單',1500)});
$('#wishForm').onsubmit=e=>{e.preventDefault();const input=$('#wishInput');if(input.value.trim()){state.wishes.push(input.value.trim());input.value='';save();renderWishes()}};$('#clearWish').onclick=()=>{state.wishes=[];save();renderWishes()};$('#reset').onclick=()=>{if(confirm('要清除這份規劃並重新開始嗎？')){localStorage.removeItem(key);state={wishes:[],pace:'悠閒渡假',days:{}};loadSetup();renderDays();renderWishes()}};
loadSetup();renderDays();renderWishes();
