const savedKey='danang-slow-shortlist-v2';
const places=[
 {id:'intercontinental',type:'resort',name:'InterContinental Danang Sun Peninsula',short:'山茶半島・隱世奢華',lat:16.1187,lng:108.2865,why:'坐落山茶半島自然保護區，面向私密海灣；適合想把森林、海景與頂級餐飲都留在飯店裡的人。',tags:['私密海灣','設計感','美食'],official:'https://blog.golavisa.co/vietnam-travel/vietnam-danang-travel-guide/',map:'InterContinental Danang Sun Peninsula Resort'},
 {id:'tia',type:'resort',name:'TIA Wellness Resort',short:'農水海灘・療癒充電',lat:16.0207,lng:108.2538,why:'私人泳池 villa 與 Wellness Inclusive 概念，把 SPA、呼吸練習與慢下來的節奏排進住宿本身。',tags:['身心療癒','私人泳池','SPA'],official:'https://blog.golavisa.co/vietnam-travel/vietnam-danang-travel-guide/',map:'TIA Wellness Resort Da Nang'},
 {id:'hyatt',type:'resort',name:'Hyatt Regency Danang',short:'農水海灘・親子與平衡',lat:16.0009,lng:108.2634,why:'海灘、VIE Spa、水上活動與兒童活動兼具；適合同行者需求不同、又不想犧牲度假感的一群人。',tags:['親子友善','水上活動','SPA'],official:'https://blog.golavisa.co/vietnam-travel/vietnam-danang-travel-guide/',map:'Hyatt Regency Danang Resort and Spa'},
 {id:'naman',type:'resort',name:'Naman Retreat',short:'農水海灘・靜謐設計',lat:15.9888,lng:108.2699,why:'以越南竹構建築和成熟的 SPA 風格聞名；若你想住在設計感更強、距離五行山不遠的海邊，值得比較。',tags:['設計旅宿','靜謐','SPA'],official:'https://blog.golavisa.co/vietnam-travel/vietnam-danang-travel-guide/',map:'Naman Retreat Da Nang'},
 {id:'namhai',type:'resort',name:'Four Seasons Resort The Nam Hai',short:'會安・海岸隱居',lat:15.9138,lng:108.3266,why:'在會安北側的海岸，適合把重心放在慢住、文化體驗與會安古鎮的傍晚；適合行程天數較寬裕時。',tags:['會安基地','文化感','海岸'],official:'https://blog.golavisa.co/vietnam-travel/vietnam-danang-travel-guide/',map:'Four Seasons Resort The Nam Hai Hoi An'},
 {id:'furama',type:'resort',name:'Furama Resort Danang',short:'美溪南段・經典海灘度假',lat:16.0217,lng:108.2548,why:'老牌海灘渡假村，綠意庭園與私人海灘兼具；適合第一次到峴港、希望交通與度假感都取得平衡的人。',tags:['經典度假','海灘','親子'],official:'https://www.bring-you.info/zh-tw/da-nang-accommodations',map:'Furama Resort Danang'},
 {id:'premier',type:'resort',name:'Premier Village Danang Resort',short:'美溪南段・私人 Villa',lat:16.0402,lng:108.2487,why:'以獨棟泳池 Villa 為主，適合多人同行、家庭或想擁有較多私人空間的旅程。',tags:['私人泳池','多人同行','Villa'],official:'https://www.bring-you.info/zh-tw/da-nang-accommodations',map:'Premier Village Danang Resort Managed by Accor'},
 {id:'pullman',type:'resort',name:'Pullman Danang Beach Resort',short:'美溪南段・便利海灘基地',lat:16.0363,lng:108.2508,why:'有私人海灘，也較靠近餐廳與市區生活機能；適合不想完全隱居、仍想方便外食與散步的人。',tags:['生活機能','私人海灘','便利'],official:'https://mamahuhu.blog/overseas/da-nang-hotels/',map:'Pullman Danang Beach Resort'},
 {id:'sheraton',type:'resort',name:'Sheraton Grand Danang Resort',short:'農水海灘・寬闊園區',lat:15.9920,lng:108.2704,why:'農水海灘上的大型海濱渡假村，空間感與度假設施完整；適合想把多數時間留在園區的人。',tags:['大型園區','海濱','親子'],official:'https://www.bring-you.info/zh-tw/da-nang-accommodations',map:'Sheraton Grand Danang Resort & Convention Center'},
 {id:'melia',type:'resort',name:'Meliá Danang Beach Resort',short:'農水海灘・The Level 禮遇',lat:15.9970,lng:108.2690,why:'海灘、Villa 與 The Level 服務是特色；適合希望有度假感、又想保有房型與服務選擇彈性的人。',tags:['The Level','Villa','海景'],official:'https://www.pullman-danang.com/zh-hans/destination/travel-tips/connecting-room-in-da-nang/',map:'Meliá Danang Beach Resort'},
 {id:'fusion',type:'resort',name:'Fusion Resort & Villas Da Nang',short:'農水南段・新式療癒 Villa',lat:15.9681,lng:108.2823,why:'位在峴港與會安之間的寧靜海岸，以 Villa、私人海灘與 Wellness 取向為主；適合想慢住、也想往會安延伸的人。',tags:['康養','新飯店','Villa'],official:'https://fusionresorts.com/danang/zh/',map:'Fusion Resort & Villas Da Nang'},
 {id:'mikazuki',type:'resort',name:'Da Nang Mikazuki Japanese Resorts & Spa',short:'徐天海灣・Onsen 與水上樂園',lat:16.1378,lng:108.0857,why:'少數不只靠泳池的渡假村：有室內外水上樂園、日式 Onsen 與日式餐飲。適合想有一兩天玩水、其餘時間放鬆的夫妻。',tags:['Onsen','水上樂園','日式餐飲'],official:'https://mikazuki.com.vn/en/',map:'Da Nang Mikazuki Japanese Resorts & Spa'},
 {id:'mercurebana',type:'resort',name:'Mercure Danang French Village Bana Hills',short:'巴拿山・雲端法式村莊',lat:15.9977,lng:107.9881,why:'巴拿山園區內的山上度假住宿；最適合將纜車、金橋、歐式村莊與夜間山景集中成一晚的特別體驗。',tags:['巴拿山','纜車','山景'],official:'https://all.accor.com/hotel/7888/index.en.shtml',map:'Mercure Danang French Village Bana Hills'},
 {id:'sontra',type:'place',name:'山茶半島與靈應寺',short:'自然・半日景觀路線',lat:16.0966,lng:108.2809,why:'森林、山路與海岸視野在同一個半島。清晨或傍晚光線舒服，也較適合不趕時間的探索。',tags:['山海景','野生動物','日落'],official:'https://www.lanytrip.com/blogs/central-vietnam-attractions/da-nang-attractions-guide',map:'Son Tra Peninsula Da Nang'},
 {id:'mykhe',type:'place',name:'美溪海灘',short:'海灘・日出與咖啡',lat:16.0602,lng:108.2463,why:'峴港最方便靠近城市的長海灘。清晨散步、游泳，或把它當成飯店外的一段鬆弛時光。',tags:['日出','城市海灘','咖啡'],official:'https://www.lanytrip.com/blogs/central-vietnam-attractions/da-nang-attractions-guide',map:'My Khe Beach Da Nang'},
 {id:'marble',type:'place',name:'五行山',short:'文化・洞穴與俯瞰',lat:16.0038,lng:108.2636,why:'石灰岩山、石窟與寺廟交織；從農水海灘一帶出發最順，建議避開正午炎熱時段。',tags:['寺廟','洞穴','登高'],official:'https://debbiechien.com/marble-mountains/',map:'Marble Mountains Da Nang'},
 {id:'hoian',type:'place',name:'會安古城',short:'夜晚・燈籠與河岸',lat:15.8801,lng:108.3380,why:'更適合傍晚抵達：逛古城、吃晚餐、沿河慢走。若住在會安北側，能把往返感降到最低。',tags:['古城','晚餐','夜景'],official:'https://debbiechien.com/danang-travel-guide/',map:'Hoi An Ancient Town'},
 {id:'haivan',type:'place',name:'海雲關',short:'公路・山海展望',lat:16.2034,lng:108.1361,why:'從峴港往北的經典海岸山路。適合預留半天以上，以包車或熟悉路況的交通方式慢慢走。',tags:['公路旅行','山海景','半日'],official:'https://www.lanytrip.com/blogs/central-vietnam-attractions/da-nang-attractions-guide',map:'Hai Van Pass'}
];
let saved=JSON.parse(localStorage.getItem(savedKey)||'[]'),activeFilter='all',map,markers=[];
let baseId='',stayStyle='resort';
const mapsUrl=p=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.map)}`;
const byId=id=>places.find(p=>p.id===id);
function save(){localStorage.setItem(savedKey,JSON.stringify(saved));renderSaved()}
function detail(p){const selected=saved.includes(p.id);document.querySelector('#placeDetail').innerHTML=`<span class="detail-kicker">${p.type==='resort'?'渡假村基地':'景點／體驗'} · ${p.short}</span><h3>${p.name}</h3><p>${p.why}</p><div class="detail-tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="detail-links"><a href="${mapsUrl(p)}" target="_blank" rel="noopener">在 Google Maps 開啟 ↗</a><a href="${p.official}" target="_blank" rel="noopener">查看相關介紹／文章 ↗</a><button class="save-place ${selected?'saved':''}" data-id="${p.id}">${selected?'已加入候選 ✓':'加入我的候選'}</button></div>`;document.querySelector('.save-place').onclick=e=>toggle(e.currentTarget.dataset.id)}
function toggle(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];save();detail(byId(id));renderCards()}
function markerIcon(type){return L.divIcon({className:'map-marker '+type,html:`<span></span>`,iconSize:[18,18],iconAnchor:[9,9]})}
function renderMarkers(){markers.forEach(m=>map.removeLayer(m));markers=[];places.filter(p=>activeFilter==='all'||p.type===activeFilter).forEach(p=>{const m=L.marker([p.lat,p.lng],{icon:markerIcon(p.type)}).addTo(map);m.on('click',()=>detail(p));markers.push(m)})}
function nearbyPlaces(base,count=2){return places.filter(p=>p.type==='place').sort((a,b)=>kmBetween(base,a)-kmBetween(base,b)).slice(0,count)}
function renderCards(){const box=document.querySelector('#resortCards');box.innerHTML=places.filter(p=>p.type==='resort').map(p=>{const nearby=nearbyPlaces(p);return `<article class="resort-card"><span>${p.short}</span><h3>${p.name}</h3><p>${p.why}</p><div class="card-compare"><b>渡假村裡可享受</b><span>${p.tags.join(' · ')}</span><b>附近最順路</b>${nearby.map(x=>`<span>${x.name}・約 ${kmBetween(p,x).toFixed(0)} km</span>`).join('')}</div><button data-id="${p.id}">${saved.includes(p.id)?'已在候選清單 ✓':'在地圖比較周邊 →'}</button></article>`}).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>{const p=byId(b.dataset.id);detail(p);map.flyTo([p.lat,p.lng],12,{duration:.7});document.querySelector('#explore').scrollIntoView({behavior:'smooth'})})}
function renderSaved(){const box=document.querySelector('#savedList');if(!saved.length){box.innerHTML='<p class="empty">還沒有候選地點。從地圖或渡假村卡開始收藏吧。</p>';return}box.innerHTML=saved.map(id=>{const p=byId(id);return `<article class="saved"><span class="saved-type">${p.type==='resort'?'渡假村基地':'景點／體驗'}</span><h3>${p.name}</h3><p>${p.short}</p><div><a href="${mapsUrl(p)}" target="_blank" rel="noopener">Google Maps ↗</a><button data-id="${p.id}">移除</button></div></article>`}).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>toggle(b.dataset.id))}
function init(){map=L.map('map',{scrollWheelZoom:false}).setView([16.01,108.27],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(map);renderMarkers();renderCards();renderSaved();const guides=['https://blog.golavisa.co/vietnam-travel/vietnam-danang-travel-guide/','https://www.lanytrip.com/blogs/central-vietnam-attractions/da-nang-attractions-guide','https://debbiechien.com/danang-travel-guide/'];document.querySelectorAll('.guide-grid a').forEach((a,i)=>a.href=guides[i]);document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderMarkers()});document.querySelector('#clearSaved').onclick=()=>{saved=[];save();renderCards()}}
function kmBetween(a,b){const r=Math.PI/180,dLat=(b.lat-a.lat)*r,dLng=(b.lng-a.lng)*r;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function renderStayMode(){let host=document.querySelector('#stayMode');if(!host){host=document.createElement('section');host.id='stayMode';host.className='stay-mode';document.querySelector('#explore').before(host)}const base=baseId?byId(baseId):null;const nearby=base?nearbyPlaces(base,3):[];const styles={resort:{name:'幾乎不出門',note:'優先看 SPA、餐飲、Villa、Onsen 或園區活動，找一間本身就值得連住的地方。'},nearby:{name:'只安排近距離小出走',note:'優先看最鄰近的山海、古鎮或文化景點；其餘時間仍留在渡假村。'},balanced:{name:'偶爾安排半日探索',note:'可接受一段車程，讓渡假村和峴港／會安各有一點份量。'}};const s=styles[stayStyle];host.innerHTML=`<div class="stay-mode-inner"><div class="base-picker"><p class="eyebrow">01 / COMPARE BEFORE YOU CHOOSE</p><h2>先看每一間能帶給你什麼，再決定住哪裡。</h2><p>不必先選渡假村。先選你想要的旅遊節奏，下面的比較卡會告訴你每間渡假村本身的亮點，以及從那裡最順路能去的地方。</p></div><div><div class="style-options">${Object.entries(styles).map(([id,item])=>`<button class="style-option ${id===stayStyle?'active':''}" data-style="${id}"><strong>${item.name}</strong><span>${item.note}</span></button>`).join('')}</div><div class="style-result"><p class="eyebrow">接著，從比較卡挑一間深入看</p><h3>${s.name}</h3><p>${s.note}</p><div class="base-choice"><label for="baseSelect">想先深入比較哪一間？</label><select id="baseSelect"><option value="">先不選，繼續往下比較</option>${places.filter(p=>p.type==='resort').map(p=>`<option value="${p.id}" ${p.id===baseId?'selected':''}>${p.name}</option>`).join('')}</select></div>${base?`<div class="nearby-list">${nearby.map(p=>`<button data-place="${p.id}">${base.name} 附近：${p.name}・約 ${kmBetween(base,p).toFixed(0)} km</button>`).join('')}</div>`:''}</div></div></div>`;document.querySelector('#baseSelect').onchange=e=>{baseId=e.target.value;renderStayMode();if(!baseId)return;const p=byId(baseId);map.flyTo([p.lat,p.lng],12,{duration:.7});detail(p);document.querySelector('#explore').scrollIntoView({behavior:'smooth'})};host.querySelectorAll('.style-option').forEach(b=>b.onclick=()=>{stayStyle=b.dataset.style;renderStayMode()});host.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{const p=byId(b.dataset.place);map.flyTo([p.lat,p.lng],13,{duration:.7});detail(p);document.querySelector('#explore').scrollIntoView({behavior:'smooth'})})}
init();renderStayMode();document.querySelector('#stayMode').after(document.querySelector('.recommendations'));document.querySelector('.hero-note b').textContent=places.filter(p=>p.type==='resort').length;
